version: "3"

services:
  vue:
    build:
      context: ./VueServer
      dockerfile: Dockerfile
    image: vue
    container_name: vue
    ports:
      - "3002:3002"
    volumes:
      - ./VueServer:/app

  node:
    build:
      context: ./NodeServer
      dockerfile: Dockerfile
    image: node
    container_name: node
    ports:
      - "3001:3001"
    volumes:
      - ./NodeServer:/app
