version: "3"

services:
  vue:
    build:
      context: ./VueServer
      dockerfile: Dockerfile
    image: vue
    container_name: vue
    ports:
      - "3002:3002"
    volumes:
      - ./VueServer:/app

  node:
    build:
      context: ./NodeServer
      dockerfile: Dockerfile
    image: node1
    container_name: node1
    ports:
      - "3001:3001"
    volumes:
      - ./NodeServer:/app

  mysql:
    build:
      context: ./Mysql
      dockerfile: Dockerfile
    image: mysql
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: mydb
      MYSQL_USER: myuser
      MYSQL_PASSWORD: mypassword
    ports:
      - "3306:3306"
    volumes:
      - ./Mysql:/app
